version: "3"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./cache:/cache
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./data/nginx/logs:/var/log/nginx
      - ./config/certificate.crt:/etc/nginx/certificate.crt
      - ./config/key.key:/etc/nginx/key.key
    ports:
      - 443:443
      - 80:80

networks:
  default:
    external:
      name: lzs_network